### PR TITLE
Update tooling and add CI configuration

### PR DESCRIPTION
**Pull request by althonos**
Hi !

In response to #202, this PR does the following things:

- [x] Rewrite the setup configuration file using [`setup.cfg`](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files) to avoid executing too much custom code in `setup.py`
- [x] Write a minimal `.travis.yml` configuration file for Travis-CI that will:
   - [x] Install the library for Python 2.7, 3.6, 3.7 and 3.8
   - [x] Attempt to build the HTML documentation of the `demo` project
   - [x] On tagged commits, build source and wheel distribution, check them, and upload them with `twine`

@ryan-roemer or any maintainer, you will need to do the following for this to be completely functional:

- [ ] Activate the project on Travis-CI.org
- [ ] Add the two following environment variables to the project configuration:
   - [ ] `TWINE_USERNAME` with your pypi.org username.
   - [ ] `TWINE_PASSWORD` with your pypi.org password.

### CODE REVIEW

**Comment by althonos** [comment]
`Makefile` and `fabfile.py` should probably be removed eventually, since most of the distribution tooling will be handled by Travis-CI if this PR gets merged.

**Comment by ryan-roemer** [comment]
Good call out for the makefile and fabfile. I’m open to removing/replacing/honing down/new tools so we have an easy task runner for the internal demo for local development

**Comment by althonos** [comment]
> Great work! I’m now sick but will try this out hopefully later this week or next. How does this handle versioning (Eg major minor patch) for what’s published?

You still do the versioning manually. You then edit the version attribute in `sphinx_bootstrap_theme/__init__.py`, make a commit, tag the commit with the same release number, and Travis-CI will perform the release cycle.

In case you didn't change the version number, the CI build will fail as PyPI doesn't allow you to upload a version that was already uploaded.

**Comment by svenevs** [comment]
Hey @althonos the changes to `setup.py` look good, Ryan and I discussed the various options and I started in on the CI changes we wanted. I'll be finishing them up this weekend.

Just wanted to ping you to say thanks and that it's not being ignored :)

**Pull request closed without merging**
